# -*- coding: utf-8 -*-
"""news_website_v2_5_2(lean_deployment_version) dev.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/embedded/projects/gen-lang-client-0889501011/locations/asia-southeast1/repositories/dd9efc1f-7d43-46ab-885f-1a76ad51bab3
"""

import pandas
import numpy
import nltk
!pip install nrclex
!pip install wordcloud
from nrclex import NRCLex

from nltk.stem.snowball import SnowballStemmer
from nltk.stem import WordNetLemmatizer

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

import re
from nltk.sentiment.vader import SentimentIntensityAnalyzer
nltk.download('vader_lexicon')
nltk.download('vader_lexicon')
nltk.download('punkt')
nltk.download('stopwords')

#!pip install newsapi-python
#!pip install unsloth datasets
#!pip install unsloth
!pip install feedparser
!pip install keybert
from keybert import KeyBERT
import feedparser
from datetime import datetime
#import newsapi
#from newsapi import NewsApiClient
#import unsloth
#from unsloth import FastLanguageModel
from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline, AutoModelForSeq2SeqLM,TextStreamer
import datasets
!pip install Flask pyngrok
#!pip install sentence-transformers
#!pip install zipnn
!pip install newspaper4k
!pip install lxml[html_clean]
!pip install ddgs
!pip install decorator==5.1.1
!pip install wbdata
!pip install world_bank_data --upgrade
!pip install --upgrade google-genai
!pip install yake

"""## Flask GUI (using NGROK since Colab is server side and flask runs locally natively)

### HTML template
"""

HTML_TEMPLATE3 = """
<!DOCTYPE html>
<html>
<head><title>Pandas Gemma</title>
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-4104808142839010"crossorigin="anonymous"></script>
<meta name="monetag" content="1eeb85e936244c2884fa20a172b88056">
</head>
<body>

<style>
.hidden {
    display: none;
}
</style>

<style>

/* Sets the color of the separator for plotly's graphs */
hr {
    border-color: blue; /* Sets the color of the line */
    border-width: 3px;  /* Sets the thickness of the line */
    border-style: solid; /* Sets the style of the line */
    background-color: transparent; /* Ensures the background doesn't interfere */
  }

  /* 🧭 NAVIGATION BAR */
  .navbar {
    background-color: #1a1a1a;
    overflow: visible;             /* ✅ allow dropdown to overflow */
    position: sticky;
    top: 0;
    z-index: 1000;
    width: 100%;
    box-shadow: 0 2px 8px rgba(0,0,0,0.2);
    padding: 8px 0;
  }

  nav-container {
  display: flex;
  flex-wrap: wrap;
  justify-content: flex-start;   /* ✅ align all buttons to the left */
  align-items: center;
  gap: 5px;
  padding-left: 20px;            /* optional padding for spacing from edge */
  overflow: visible;
}

  .dropbtn {
    background-color: #1a1a1a;
    color: white;
    padding: 10px 14px;
    font-size: 14px;
    border: none;
    cursor: pointer;
    font-weight: bold;
    white-space: nowrap;
  }

  .dropdown {
    position: relative;
    display: inline-block;
    overflow: visible;            /* ✅ allows dropdown content to display fully */
  }

  .dropdown-content {
    display: none;
    position: absolute;
    top: 100%;                    /* ✅ place it right below button */
    left: 0;
    background-color: white;
    min-width: 200px;
    max-height: 400px;            /* optional: limit height */
    overflow-y: auto;             /* ✅ scroll inside if too tall */
    box-shadow: 0px 4px 12px rgba(0,0,0,0.15);
    z-index: 9999;                /* ✅ keeps it on top of other elements */
    border-radius: 6px;
  }

  .dropdown-content a {
    color: #333;
    padding: 10px 14px;
    text-decoration: none;
    display: block;
    font-size: 13px;
  }

  .dropdown-content a:hover {
    background-color: #f2f2f2;
  }

  .dropdown:hover .dropdown-content {
    display: block;
  }

  .dropdown:hover .dropbtn {
    background-color: #333;
  }

  /* Make sure category and subcategory headings aren't hidden under navbar */
h1[id], h2[id], span[id] {
  scroll-margin-top: 180px;  /* adjust to your navbar height */

 /* Special styling for Gemma button */
.gemma-btn {
  background-color: white !important;
  color: #1a1a1a !important;
  border: 1px solid #1a1a1a;
  transition: background-color 0.3s ease;
}

.gemma-btn a {
  color: #1a1a1a !important;
  text-decoration: none;

}

.gemma-btn:hover {
  background-color: #f0f0f0;
}

.gemma-btn:hover a {
  color: #000;
}



}



  </style>

  <!-- CSS for the dropdown sources table -->
  <style>
  body {
    font-family: Verdana, sans-serif;
    font-size: 11px;
    background-color: #fafafa;
    color: #222;
  }

  .highlight-text {
    max-width: 70ch;
    text-align: justify;
    margin-bottom: 8px;
  }

  /* Subcategory container — no forced width now */
  .subcat-block {
    background: #fff;
    border: 1px solid #ddd;
    border-radius: 6px;
    margin: 15px 0;
    padding: 12px;
    box-shadow: 0 1px 4px rgba(0,0,0,0.04);
  }

  /* Collapsible wrapper — now width and height are controlled externally */
  details.source-table {
    margin-top: 8px;
    background: #f9f9f9;
    border-radius: 6px;
    padding: 8px;
    border: 1px solid #ddd;
    overflow: auto; /* allows scroll if small height */
  }

  /* Optional helper class for setting dimensions */
  .resizable-table {
    width: var(--table-width, auto);
    height: var(--table-height, auto);
  }

  details summary {
    cursor: pointer;
    font-weight: bold;
    color: #007acc;
    margin-bottom: 5px;
  }
  details[open] summary {
    color: #005fa3;
  }

  table {
    width: 100%;
    border-collapse: collapse;
    margin-top: 4px;
    font-size: 10px;
  }

  th {
    background-color: #e0e0e0;
    text-align: left;
    padding: 4px;
    border-bottom: 2px solid #ccc;
  }

  td {
    padding: 4px;
    vertical-align: top;
    border-bottom: 1px solid #eee;
  }

  td.title {
    font-weight: bold;
    width: 30%;
  }

  td.summary {
    width: 55%;
    text-align: justify;
  }

  td.feed {
    width: 15%;
    color: #666;
    font-style: italic;
  }

  details[open] table {
    animation: fadeIn 0.25s ease-in;
  }

  @keyframes fadeIn {
    from {opacity: 0;}
    to {opacity: 1;}
  }
</style>

<style>
body {
    font-family: Arial, sans-serif;
    margin: 0;
    padding: 0;
}

.tab {
    overflow: hidden;
    border-bottom: 1px solid #ccc;
    background: #f4f4f4;
}

.tab button {
    background: inherit;
    border: none;
    outline: none;
    cursor: pointer;
    padding: 12px 18px;
    transition: background 0.2s;
    font-size: 16px;
}

.tab button:hover {
    background: #ddd;
}

.tab button.active {
    background: white;
    border-bottom: 2px solid #000;
}

.tabcontent {
    display: none;
    padding: 20px;
}
</style>



  <!-- 📰 Horizontal Navigation Bar -->
  <nav class="navbar">
  <div class="nav-container">

    <button class="dropbtn"><a href="https://news.ngrok.dev/"><b style="color:GhostWhite;">HOME </b></a></button>

    <div class="dropdown">
      <button class="dropbtn"><b style="color:GhostWhite;">World Bank Plots ▼</b></button>
      <div class="dropdown-content">
        {% for plot_name, plot in wbplots %}
          <a href="#{{ plot_name }}">{{ plot_name }}</a>
        {% endfor %}
      </div>
    </div>

    <div class="dropdown">
    <button class="dropbtn gemma-btn"><a href="/pandas" style="color:white; text-decoration:none;">Ask a Panda!</a></button>
    <button class="dropbtn gemma-btn"><a href="/find" style="color:white; text-decoration:none;">Internet Gemma 3!</a></button>
    </div>
  </div>
  </nav>

    <h1 style = 'font-size: 35px;'>Ask a Panda!</h1>
    <form action="/ask" method="post" ,="" name="form">
      <p style = 'font-size: 14px;'><strong>News Article URL:</strong></p>
      <input type="text" ,="" size="30" id="url" name="url" placeholder="What is the URL?">
      <div><details class="source-table" style="width: 400px;">
      <summary>🌐 Advanced Options</summary>
      <p style = 'font-size: 14px;'><strong>Should LLM include relevant World Bank data? (~10s - 40s longer) </strong></p>
      <input type="checkbox" id="include" name="include" value="Yes">
      <label for="include">Yes</label>
      <p style = 'font-size: 14px;'><strong>Maximum limit of world bank sources selected(default: 2)(~more sources, the longer) </strong></p>
      <input type="range" id="amt" name="amt" min="1" max="10" value="2" step="1" oninput="this.nextElementSibling.value = this.value"><output>2</output>
      <p style = 'font-size: 14px;'><strong>Should relevant World Bank data include description? (~40s - 2m longer) </strong></p>
      <input type="checkbox" id="include_desc" name="include_desc" value="Yes">
      <label for="include_desc">Yes</label><br><br>
      </details></div>
      <!--<p><strong>Chart Type:</strong></p>
      <label><input type="radio" ,="" size="30" id="chart1" name="chart" value="bar"> Bar Chart</label><br><br>
      <label><input type="radio" ,="" size="30" id="chart2" name="chart" value="line"> Line Chart</label><br><br>
      <label><input type="radio" ,="" size="30" id="chart3" name="chart" value="pie"> Pie Chart</label><br><br>-->
      <br><br>
      <button value="Submit">Reply</button>
      <br><br>
    </form>

    <div class="{% if not show_section %}hidden{% endif %}">
    <p style = 'font-size: 24px;  text-align: center;'><b style="color:Tomato;">Gemma's Responses:</b></p>
    <p style="max-width: 85ch; text-align: justify;  white-space: pre-wrap; font-size: 14px;"><b>Gemma's summary:</b> {{ summary | e }}</p><br><br><br><br>
    <p style = 'font-size: 24px;  text-align: center;'><b style="color:Tomato;">Pandas and Plotly's reply:</b></p><br><br>
    <p style = 'font-size: 18px;  text-align: center;'><b style="color:Orange;">Extracted from news article:</b></p>
    {{ reply | safe }}
    {{ table1 | safe }}<br><br><br><br><br>

    <p style = 'font-size: 18px; text-align: center;'><b style="color:Orange;">News article Sentiments:</b></p>
    {{ wc1 | safe}}
    {{ wc2 | safe}}
    <br><br><br><br><br>
    {{ reply2 | safe }}
    {{ table2 | safe }}<br><br><br><br><br>

    <!--<div><details class="source-table">
      <summary><p style = 'font-size: 14px;  text-align: center;'><b style="color:Tomato;">🖍️ View highlighted Article:</b></p></summary>

      <p id="hl">
        {{ hl | safe }}
      </p>

    </details></div>
    <br><br><br><br><br> -->

    <p style = 'font-size: 24px;  text-align: center;'><b style="color:Tomato;"><i>Optional:</i></b></p>
    <div><details class="source-table">
      <summary><p style = 'font-size: 14px;  text-align: center;'><b style="color:Tomato;">Relevant World Bank Data:</b></p></summary>
    {% for plot_name, plot in wbplots %}

      <span id="{{ plot_name }}">
        {{ plot | safe }}
      </span>
    {% endfor %}
    </details></div>
    <br><br>


    <div>
    <details class="source-table">
        <summary><strong>📈 Description for World Bank Charts</strong></summary>
        <table>
        {% for plot_name, plot_desc in desc %}
          <thead>
            <tr>
              <th><p style = 'font-size: 14px;  text-align: center;'><b style="color:Tomato;">{{ plot_name }}</b></p></th>
            </tr>
          </thead>
          <tbody>
              <tr>
                <td class="desc">{{ plot_desc | safe }}</td>
              </tr>
          </tbody>
        {% endfor %}
        </table>
      </details>
    </div>

    </div>

    <br><br><br><br><br>
    <a href="https://www.worldbank.org/en/about/legal/terms-of-use-for-datasets"><p style="font-size: 8px;">World Bank Open Data is under CC BY 4.0</p></a>
    <a href="https://creativecommons.org/licenses/by/4.0/"><p style="font-size: 8px;">CC BY 4.0</p></a>
    <a href="https://ai.google.dev/gemma/prohibited_use_policy"><p style="font-size: 8px;">Gemma Restricted Use Policy</p></a>
    <a href="https://ai.google.dev/gemma/terms"><p style="font-size: 8px;">Gemma T&C</p></a>
</body>
</html>
"""

HTML_TEMPLATE4 = """
<!DOCTYPE html>
<html>
<head><title>Internet Gemma</title>
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-4104808142839010"crossorigin="anonymous"></script>
<meta name="monetag" content="1eeb85e936244c2884fa20a172b88056">
</head>
<body>

<style>
.hidden {
    display: none;
}
</style>

<style>
/* Sets the color of the separator for plotly's graphs */
hr {
    border-color: blue; /* Sets the color of the line */
    border-width: 3px;  /* Sets the thickness of the line */
    border-style: solid; /* Sets the style of the line */
    background-color: transparent; /* Ensures the background doesn't interfere */
  }

  /* 🧭 NAVIGATION BAR */
  .navbar {
    background-color: #1a1a1a;
    overflow: visible;             /* ✅ allow dropdown to overflow */
    position: sticky;
    top: 0;
    z-index: 1000;
    width: 100%;
    box-shadow: 0 2px 8px rgba(0,0,0,0.2);
    padding: 8px 0;
  }

  nav-container {
  display: flex;
  flex-wrap: wrap;
  justify-content: flex-start;   /* ✅ align all buttons to the left */
  align-items: center;
  gap: 5px;
  padding-left: 20px;            /* optional padding for spacing from edge */
  overflow: visible;
}

  .dropbtn {
    background-color: #1a1a1a;
    color: white;
    padding: 10px 14px;
    font-size: 14px;
    border: none;
    cursor: pointer;
    font-weight: bold;
    white-space: nowrap;
  }

  .dropdown {
    position: relative;
    display: inline-block;
    overflow: visible;            /* ✅ allows dropdown content to display fully */
  }

  .dropdown-content {
    display: none;
    position: absolute;
    top: 100%;                    /* ✅ place it right below button */
    left: 0;
    background-color: white;
    min-width: 200px;
    max-height: 400px;            /* optional: limit height */
    overflow-y: auto;             /* ✅ scroll inside if too tall */
    box-shadow: 0px 4px 12px rgba(0,0,0,0.15);
    z-index: 9999;                /* ✅ keeps it on top of other elements */
    border-radius: 6px;
  }

  .dropdown-content a {
    color: #333;
    padding: 10px 14px;
    text-decoration: none;
    display: block;
    font-size: 13px;
  }

  .dropdown-content a:hover {
    background-color: #f2f2f2;
  }

  .dropdown:hover .dropdown-content {
    display: block;
  }

  .dropdown:hover .dropbtn {
    background-color: #333;
  }

  /* Make sure category and subcategory headings aren't hidden under navbar */
h1[id], h2[id], span[id] {
  scroll-margin-top: 180px;  /* adjust to your navbar height */

 /* Special styling for Gemma button */
.gemma-btn {
  background-color: white !important;
  color: #1a1a1a !important;
  border: 1px solid #1a1a1a;
  transition: background-color 0.3s ease;
}

.gemma-btn a {
  color: #1a1a1a !important;
  text-decoration: none;

}

.gemma-btn:hover {
  background-color: #f0f0f0;
}

.gemma-btn:hover a {
  color: #000;
}



}



  </style>

  <!-- CSS for the dropdown sources table -->
<style>
  body {
    font-family: Verdana, sans-serif;
    font-size: 11px;
    background-color: #fafafa;
    color: #222;
  }

  .highlight-text {
    max-width: 70ch; /* narrower text width */
    text-align: justify;
    margin-bottom: 8px;
  }

  /* Subcategory block */
  .subcat-block {
    background: #fff;
    border: 1px solid #ddd;
    border-radius: 6px;
    margin: 15px 0;
    padding: 12px;
    box-shadow: 0 1px 4px rgba(0,0,0,0.04);
    max-width: 600px; /* <<< makes the whole block narrower */
  }

  /* Collapsible sources */
  details.advanced-table {
    margin-top: 8px;
    background: #f9f9f9;
    border-radius: 6px;
    padding: 8px;
    border: 1px solid #ddd;
    max-width: 580px; /* <<< narrower */
  }



  /* Fade animation */
  details[open] table {
    animation: fadeIn 0.25s ease-in;
  }

  @keyframes fadeIn {
    from {opacity: 0;}
    to {opacity: 1;}
  }
</style>


  <style>
  body {
    font-family: Verdana, sans-serif;
    font-size: 11px;
    background-color: #fafafa;
    color: #222;
  }

  .highlight-text {
    max-width: 70ch;
    text-align: justify;
    margin-bottom: 8px;
  }

  /* Subcategory container — no forced width now */
  .subcat-block {
    background: #fff;
    border: 1px solid #ddd;
    border-radius: 6px;
    margin: 15px 0;
    padding: 12px;
    box-shadow: 0 1px 4px rgba(0,0,0,0.04);
  }

  /* Collapsible wrapper — now width and height are controlled externally */
  details.source-table {
    margin-top: 8px;
    background: #f9f9f9;
    border-radius: 6px;
    padding: 8px;
    border: 1px solid #ddd;
    overflow: auto; /* allows scroll if small height */
  }

  /* Optional helper class for setting dimensions */
  .resizable-table {
    width: var(--table-width, auto);
    height: var(--table-height, auto);
  }

  details summary {
    cursor: pointer;
    font-weight: bold;
    color: #007acc;
    margin-bottom: 5px;
  }
  details[open] summary {
    color: #005fa3;
  }

  table {
    width: 100%;
    border-collapse: collapse;
    margin-top: 4px;
    font-size: 10px;
  }

  th {
    background-color: #e0e0e0;
    text-align: left;
    padding: 4px;
    border-bottom: 2px solid #ccc;
  }

  td {
    padding: 4px;
    vertical-align: top;
    border-bottom: 1px solid #eee;
  }

  td.title {
    font-weight: bold;
    width: 30%;
  }

  td.summary {
    width: 55%;
    text-align: justify;
  }

  td.feed {
    width: 15%;
    color: #666;
    font-style: italic;
  }

  details[open] table {
    animation: fadeIn 0.25s ease-in;
  }

  @keyframes fadeIn {
    from {opacity: 0;}
    to {opacity: 1;}
  }
</style>



  <!-- 📰 Horizontal Navigation Bar -->
  <nav class="navbar">
  <div class="nav-container">

    <button class="dropbtn"><a href="https://news.ngrok.dev/"><b style="color:GhostWhite;">HOME </b></a></button>

    <div class="dropdown">
      <button class="dropbtn"><b style="color:GhostWhite;">World Bank Plots ▼</b></button>
      <div class="dropdown-content">
        {% for plot_name, plot in wbplots %}
          <a href="#{{ plot_name }}">{{ plot_name }}</a>
        {% endfor %}
      </div>
    </div>

    <div class="dropdown">
    <button class="dropbtn gemma-btn"><a href="/pandas" style="color:white; text-decoration:none;">Ask a Panda!</a></button>
    <button class="dropbtn gemma-btn"><a href="/find" style="color:white; text-decoration:none;">Internet Gemma 3!</a></button>
    </div>
  </div>
  </nav>

    <h1 style = 'font-size: 35px;'>Internet Gemma!</h1>
    <form action="/search" method="post" name="form">
      <p style = 'font-size: 14px;'><strong>Search Term (to scrape from DDG):</strong></p>
      <input type="text" ,="" size="30" id="topic" name="topic" placeholder="What is the term?">
      <div><details class="source-table" style="width: 400px;">
      <summary>🔍 Customize Seearch Options</summary>
      <p style = 'font-size: 14px;'><strong>Initial Sample size (to generate categories):</strong></p>
      <input type="range" id="sample" name="sample" min="50" max="500" value="100" oninput="this.nextElementSibling.value = this.value"><output>100</output><br><br>
      <p style = 'font-size: 14px;' ><strong>Articles Scraped (per category):</strong></p>
      <input type="range" id="num" name="num" min="100" max="1000" value="500" oninput="this.nextElementSibling.value = this.value"><output>500</output><br><br>
      <p style = 'font-size: 14px;'><strong>Region (default:wt-wt):</strong></p>
      <input type="text" value='wt-wt' size="30" id="region" name="region" placeholder="wt-wt">
      <p style = 'font-size: 14px;'>Region list: wt-wt,us-en,uk-en,ru-ru,cn-zh</p>
      </details></div>

      <div><details class="source-table" style="width: 400px;">
      <summary>🌐 Advanced Options</summary>
      <p style = 'font-size: 14px;'><strong>Should LLM include relevant World Bank data? (~10s - 40s longer) </strong></p>
      <input type="checkbox" id="include" name="include" value="Yes">
      <label for="include">Yes</label>
      <p style = 'font-size: 14px;'><strong>Maximum limit of world bank sources selected(default: 2)(~more sources, the longer) </strong></p>
      <input type="range" id="amt" name="amt" min="1" max="10" value="2" step="1" oninput="this.nextElementSibling.value = this.value"><output>2</output>
      <p style = 'font-size: 14px;'><strong>Should relevant World Bank data include a description? (~40s -2m longer) </strong></p>
      <input type="checkbox" id="include_desc" name="include_desc" value="Yes">
      <label for="include_desc">Yes</label><br><br>
      </details></div>
      <br><br>
      <button value="Submit">Reply</button>
    </form>
    <br><br><br>

    <div class="{% if not show_section %}hidden{% endif %}">
    <p style = 'font-size: 24px;  text-align: center;'><b style="color:Tomato;">Gemma's Responses:</b></p>
    <p style="max-width: 85ch; text-align: justify;  white-space: pre-wrap; font-size: 14px;"><b>Gemma's report:</b> {{ reply1 | e }}</p><br><br>
    <p style="max-width: 85ch; text-align: justify;  white-space: pre-wrap; font-size: 14px;"><b>Gemma's Explanation:</b> {{ reply2 | e }}</p><br>
    <p style="max-width: 85ch; text-align: justify;  white-space: pre-wrap; font-size: 14px;"><b>Gemma's Strategies:</b> {{ reply3 | e }}</p><br>
    <br><br><br>
    <div>
    <details class="source-table">
        <summary><strong>📚 Sources for Gemma's Response</strong></summary>
        <table>
          <thead>
            <tr>
              <th>Feed</th>
            </tr>
          </thead>
          <tbody>
            {% for feed in feeds %}
              <tr>
                <td class="feed">{{ feed }}</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </details>
    </div>
    <br><br>

    <p style = 'font-size: 24px;  text-align: center;'><b style="color:Tomato;"><i>Optional:</i></b></p>
    <div><details class="source-table">
      <summary><p style = 'font-size: 14px;  text-align: center;'><b style="color:Tomato;">Relevant World Bank Data:</b></p></summary>
    {% for plot_name, plot in wbplots %}

      <span id="{{ plot_name }}">
        {{ plot | safe }}
      </span>
    {% endfor %}
    </details></div>
    <br><br>


    <div>
    <details class="source-table">
        <summary><strong>📈 Description for World Bank Charts</strong></summary>
        <table>
        {% for plot_name, plot_desc in desc %}
          <thead>
            <tr>
              <th><p style = 'font-size: 14px;  text-align: center;'><b style="color:Tomato;">{{ plot_name }}</b></p></th>
            </tr>
          </thead>
          <tbody>
              <tr>
                <td class="desc">{{ plot_desc | safe }}</td>
              </tr>
          </tbody>
        {% endfor %}
        </table>
      </details>
    </div>
    <br><br>

    </div>

    <a href="https://www.worldbank.org/en/about/legal/terms-of-use-for-datasets"><p style="font-size: 8px;">World Bank Open Data is under CC BY 4.0</p></a>
    <a href="https://creativecommons.org/licenses/by/4.0/"><p style="font-size: 8px;">CC BY 4.0</p></a>
    <a href="https://serpapi.com/duckduckgo-regions"><p style="font-size: 8px;">DDG available regions</p></a>
    <a href="https://ai.google.dev/gemma/prohibited_use_policy"><p style="font-size: 8px;">Gemma Restricted Use Policy</p></a>
    <a href="https://ai.google.dev/gemma/terms"><p style="font-size: 8px;">Gemma T&C</p></a>
</body>
</html>
"""
HTML_TEMPLATE5 = """
<!DOCTYPE html>
<html>
<head><title>Pandas Gemma</title></head>
<body>
  <h1 style= 'font-size: 35px;'>{{ error }}: {{ textbox }} </h1>
</body>
"""

"""### Python Flask Code (to respond and use the template variables {{variables}} and accept POST form input using request.form['name of HTML input tag not id'] )

### Flask final
"""

#!pip install Flask pyngrok
from flask import Flask
from flask import render_template, render_template_string, request, redirect, url_for
import re
from google.colab import ai
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, AutoModelForCausalLM
import newspaper
import io
import base64
import pandas
import numpy
import plotly.express as px
nltk.download('punkt_tab')
from nrclex import NRCLex
from nltk.stem.snowball import SnowballStemmer
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import re
from nltk.sentiment.vader import SentimentIntensityAnalyzer
from wordcloud import WordCloud
import wbdata
import world_bank_data as wb
from google import genai
from google.genai.types import HttpOptions
from google.genai import types
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.decomposition import LatentDirichletAllocation
#from llama_cpp import Llama

app = Flask(__name__)

@app.route('/pandas')
def pandas():
  return render_template_string(HTML_TEMPLATE3, reply="")

#remember to remove during replacement
@app.route('/')
def home():
  return render_template_string(HTML_TEMPLATE3, reply="")

@app.route('/ask', methods=['POST'])
def ask():
  import time
  start = time.time()
  import pandas
  import plotly.express as px
  import re
  from sklearn.feature_extraction.text import CountVectorizer
  from sklearn.decomposition import LatentDirichletAllocation
  import numpy
  from plotly.subplots import make_subplots
  import yake
  url = request.form["url"]
  amt = request.form["amt"]
  try:
    include_desc = request.form["include_desc"]
  except:
    include_desc = "No"
  try:
    include = request.form["include"]
  except:
    include = "No"

  if url == "":
    return render_template_string(HTML_TEMPLATE5, error = "TEXTBOX ERROR", textbox="URL")
  try:
    article = newspaper.article(url)
  except:
    return render_template_string(HTML_TEMPLATE5, error = "ARTICLE DOWNLOAD ERROR", textbox="")
  prompt = article.text
  #new updated replaced version instead of google.colab.ai module
  client = genai.Client(http_options=HttpOptions(api_version="v1"),api_key=)

  summary = client.models.generate_content(model="gemini-2.5-flash-lite",contents=f" Summarize: [{prompt}]. Read but do not print these instructions in output: Print only executive summary (include numbers,if any) and a appropriate title, Separate the summary and title with a * , no chit-chat. Filter out all boilerplate words and noise. DO NOT add in hallucinated noise. Leave 4 nextlines after response.",)
  summary = re.sub(r'\\[a-zA-Z]+|[\${}*#]', '', str(summary.text))
  ### too long
  #import spacy
  #nlp = spacy.load("en_core_web_sm")
  #doc = nlp(prompt)

  #for ent in doc.ents:
  #    print(ent.text, ent.label_)

  #from spacy import displacy
  #hl = displacy.render(doc, style="ent", jupyter=False, page = False, minify=True) ###

  ### singular terms, too confusing for audience
  #def get_topic_keywords_sklearn(prompt, k=10):
  #  prompt = [prompt]
  #  vectorizer = CountVectorizer(stop_words = 'english')
  #  dtm_tf = vectorizer.fit_transform(prompt)
  #  lda_model = LatentDirichletAllocation(n_components=2, random_state=0)
  #  lda_model.fit(dtm_tf)

  #  words = vectorizer.get_feature_names_out()
  #  topics = {}

  #  for topic_idx, topic_weights in enumerate(lda_model.components_):
  #      top_indices = topic_weights.argsort()[::-1][:k]
  #      top_words = [(words[i], topic_weights[i]) for i in top_indices]
  #      topics[f"Topic {topic_idx}"] = top_words

  #  return topics

  ## have non-unique ngrams
  #def extract_ngrams(text, ngram_range=(1,2), top_k=20):
  #  vec = CountVectorizer(ngram_range=ngram_range, stop_words='english')
  #  X = vec.fit_transform([text])

  #  counts = X.toarray().sum(axis=0)
  #  vocab = vec.get_feature_names_out()

  #  df = pandas.DataFrame({
  #      "ngram": vocab,
  #      "frequency": counts
  #  }).sort_values("frequency", ascending=False)

  #  return df.head(top_k)

  #temp = get_topic_keywords_sklearn(prompt, k=30)
  #tempt1 = pandas.DataFrame(temp["Topic 0"])
  #tempt2 = pandas.DataFrame(temp["Topic 1"])
  #img1 = px.bar(tempt1.rename(columns={0: "terms", 1: "weight"}), x="terms", y="weight", title='Topic 1 Term Importance', text_auto=True)
  #img1.update_xaxes(tickangle=90)
  #img1.update_traces(textposition='outside', textfont_size=14,textfont_color='black')
  #img1.update_layout(height=900)

  #img3 = px.bar(tempt2.rename(columns={0: "terms", 1: "weight"}), x="terms", y="weight", title='Topic 2 Term Importance', text_auto=True)
  #img3.update_xaxes(tickangle=90)
  #img3.update_traces(textposition='outside', textfont_size=14,textfont_color='black')
  #img3.update_layout(height=900)

  ### too confusing for audience
  #start1 = time.time()
  #temp = extract_ngrams(prompt, ngram_range=(2,3), top_k=10)
  #kw = yake.KeywordExtractor(n=3, top=20)
  #temp = pandas.DataFrame(kw.extract_keywords(prompt) )
  #temp[2] = 1/temp[1]
  #img2 = px.bar(temp.rename(columns={0: "ngrams", 2: "weight"}), x="ngrams", y="weight", title='N-gram Weights', text_auto=True)
  #img2.update_xaxes(tickangle=90)
  #img2.update_traces(textposition='outside', textfont_size=14,textfont_color='black')
  #img2.update_layout(height=900,xaxis_title="N-gram", yaxis_title='Weight')
  #end = time.time()
  #print(end-start1)
  # Create empty subplot layout
  #sub = make_subplots(rows=1, cols=3, subplot_titles=("N-gram", "Topic 1 Term Importance", "Topic 2 Term Importance"))

  # Add traces from ngram
  #for trace in img2.data:
  #    sub.add_trace(trace, row=1, col=1)

  #for trace in img1.data:
  #    sub.add_trace(trace, row=1, col=2)

  #for trace in img3.data:
  #    sub.add_trace(trace, row=1, col=3)

  # could do a for loop, my mom's screaming so no
  #sub.update_xaxes(title_text=img2.layout.xaxis.title.text, row=1, col=1)
  #sub.update_xaxes(title_text=img1.layout.xaxis.title.text, row=1, col=2)
  #sub.update_xaxes(title_text=img3.layout.xaxis.title.text, row=1, col=3)
  #sub.update_yaxes(title_text=img2.layout.yaxis.title.text, row=1, col=1)
  #sub.update_yaxes(title_text=img1.layout.yaxis.title.text, row=1, col=2)
  #sub.update_yaxes(title_text=img3.layout.yaxis.title.text, row=1, col=3)
  #sub.update_xaxes(tickangle=90)
  #sub.update_layout(height=900, title="Keywords")
  #sub.update_traces(textposition='outside',textfont_size=14,textfont_color='black' )

  # Update layout

  #ef = sub.to_html(full_html=False, include_plotlyjs='cdn')
  #summary = ai.generate_text(f" Summarize: [{prompt}]. Read but do not print these instructions in output: Print only executive summary (include numbers,if any), no chit-chat. Filter out all boilerplate words and noise. DO NOT add in hallucinated noise. Leave 4 nextlines after response. ", model_name='google/gemma-3-27b')

  generation_config = types.GenerateContentConfig(temperature=0.4)
  response = client.models.generate_content(model="gemini-2.5-pro",contents=f" Summarize: {prompt}. \n\nYou are creating a chart. Print only the corresponding name (indicate unit within brackets) and the data point (only numbers and signs), all separated by * in a string, no chit-chat. DO NOT add in hallucinated noise. DO NOT assume. When encountering a range, take the mean. ",config=generation_config)#f" Summarize: {prompt}. \n\nYou have created a chart involving all values within website. Print only the most appropriate title for the chart, no chit-chat. Filter out all boilerplate words and noise. DO NOT add in hallucinated noise. DO NOT assume. When encountering a range, take the mean. ",#f" Summarize: [{prompt}]. Read but do not print these instructions in output: Print only executive summary (include numbers,if any), no chit-chat. Filter out all boilerplate words and noise. DO NOT add in hallucinated noise. Leave 4 nextlines after response. ",)
  ##response = ai.generate_text(f" Summarize: {prompt}. \n\nYou are creating a chart. Print only the corresponding name (indicate unit within brackets) and the data point (only numbers and signs), all separated by * in a string, no chit-chat. Filter out all boilerplate words and noise. This is your creativity allowance (0 to 100, 0 being the most truthful):0 . DO NOT add in hallucinated noise. DO NOT assume. When encountering a range, take the mean. ", model_name='google/gemma-3-27b')

  #title = ai.generate_text(f" Summarize: {prompt}. \n\nYou have created a chart involving all values within website. Print only the most appropriate title for the chart, no chit-chat. Filter out all boilerplate words and noise. DO NOT add in hallucinated noise. DO NOT assume. When encountering a range, take the mean. ", model_name='google/gemma-3-27b')
  title = client.models.generate_content(model="gemini-2.5-flash-lite",contents=f"Summarize: [{summary}]\n\nYou have created a chart involving all values within website. Print only the most appropriate title for the chart, no chit-chat. ",)#config=generation_config)
  title = title.text

  if '\n' not in response.text:
    data = response.text.split('*')
    name = []
    points = []
    for i in range(0,len(data),2):
      if data[i].strip() != '':
        points.append(data[i+1])
        name.append(data[i])
        #print(data[i],data[i+1])
    temp = pandas.DataFrame({'name':name, 'value':points})
    print(temp)
  else:
    data = response.text.split("\n")
    #print(data)
    name = []
    points = []
    for sep in data:
      if sep.strip() != '':
        sep = sep.split("*")
        print(sep)
        points.append(sep[1])
        name.append(sep[0])
    temp = pandas.DataFrame({'name':name, 'value':points})
  #### above is the google.genai replacement for google.colab.ai (notebook access only)
  new = []
  for i in temp['value'].tolist():
    new.append(re.sub(r'[A-Za-z%]', '', i) )
  temp['value'] = new

  temp['value'] = pandas.to_numeric(temp['value'], errors='coerce')
  temp = temp.loc[temp['value'] != numpy.nan]

  bdata1 = temp.to_html(index=False, justify='center').replace('<td>', '<td align="center">').replace('<th>','<th style="text-align: center;">')
  img = px.bar(temp, x='name', y='value', title=title, text_auto=True)
  img.update_xaxes(tickangle=90)
  img.update_traces(textposition='outside', textfont_size=14,textfont_color='black')
  img.update_layout(height=900)
  reply = img.to_html(full_html=False, include_plotlyjs='cdn')
  #img = temp.plot.bar(x='name', y='value', rot=90)
  ##Save to bytes buffer
  #buf= io.BytesIO()
  #plt.savefig(buf, format='png',bbox_inches='tight')
  #buf.seek(0)

  #reply = img_base64 = base64.b64encode(buf.getvalue()).decode('utf-8')

  #chart1 = request.form["chart1"]
  #chart2 = request.form["chart2"]
  #chart3 = request.form["chart3"]

  emotion_analyzer = NRCLex(prompt)

  temp = pandas.DataFrame( emotion_analyzer.affect_frequencies, index=['emotions']).T
  temp.columns = ['value']
  temp['emotions'] = temp.index
  temp = temp[['emotions','value']]
  temp = temp.loc[temp.emotions != 'anticip']
  img = px.bar(temp, x='emotions', y='value', title = 'NRC Sentiments', text_auto=True)
  img.update_xaxes(tickangle=45)
  img.update_traces(textposition='outside', textfont_size=14,textfont_color='black')
  img.update_layout(height=700)
  reply2 = img.to_html(full_html=False, include_plotlyjs='cdn')
  bdata2 = temp.to_html(index=False).replace('<td>', '<td align="center">').replace('<th>','<th style="text-align: center;">')

  ### new replacement in-place of 2nd wordcloud(stemmed)
  #img = px.pie(temp.loc[temp.emotions.isin(['fear','anticipation','joy','disgust','sadness','surprise','trust','anger','fear'])], names='emotions', values='value', color="emotions",color_discrete_map={"positive": "blue","negative": "red"},title = 'Sentiment Gauge')
  #img.update_traces(hole=0.55,rotation=180,textposition="inside", textfont_size=14,textfont_color='black',textinfo="percent+label")
  #img.update_layout(height=700, margin=dict(l=20, r=20, t=40, b=20), piecolorway=["blue", "red"])


  img = px.pie(temp.loc[temp.emotions.isin(['positive','negative'])],names="emotions",values="value",color="emotions",color_discrete_map={"positive": "blue","negative": "red"},title="Sentiment Gauge")
  img.update_traces(hole=0.55,textposition="inside",textinfo="percent+label",rotation=60,pull=[0.05, 0.05, 0.05])
  img.update_layout(height=450,margin=dict(l=20, r=20, t=40, b=20), piecolorway=["blue", "red"] )
  ef = img.to_html(full_html=False, include_plotlyjs='cdn')

  sentence = re.sub(r'[^\w\s]', '', prompt)
  snowstem = SnowballStemmer("english")
  stop_words = set(stopwords.words('english'))

  stopped = [word for word in word_tokenize(sentence.lower() ) if word.lower() not in stop_words]
  stemmed = [snowstem.stem(word) for word in stopped]

  x, y = numpy.ogrid[:300, :300]
  mask = (x - 150) ** 2 + (y - 150) ** 2 > 130 ** 2
  mask = 255 * mask.astype(int)
  wc1 = WordCloud(mask = mask,background_color ='white', repeat=False, prefer_horizontal = 0.66, max_words = 30, stopwords = stop_words, min_font_size = 10, max_font_size = 40).generate(sentence)
  wc2 = WordCloud(mask = mask,background_color ='white', repeat=False, prefer_horizontal = 0.66, max_words = 30, stopwords = stop_words, min_font_size = 10, max_font_size = 40).generate(" ".join(stemmed))

  img = numpy.array(wc1)
  fig = px.imshow(img)
  import plotly.io as pio
  from PIL import Image
  fig.update_xaxes(showticklabels=False).update_yaxes(showticklabels=False)
  fig.update_layout(title='News Article Word Cloud [Unstemmed]', margin = dict(l=0,r=0,t=40,b=0) )
  fig1 = pio.to_html(fig, full_html=False)

  #wc2.to_image().save(img_buffer, format='PNG')
  #encoded_image = base64.b64encode(img_buffer.getvalue()).decode()
  ## Create a Plotly figure with the word cloud image
  #fig2 = px.imshow(wc2.to_array(), binary_string=True, title="News Article Word Cloud [Stemmed]").update_xaxes(showticklabels=False).update_yaxes(showticklabels=False)
  #fig2 = fig2.to_html(full_html=False, include_plotlyjs='cdn')

  img = numpy.array(wc2)
  fig = px.imshow(img)
  import plotly.io as pio
  from PIL import Image
  fig.update_xaxes(showticklabels=False).update_yaxes(showticklabels=False)
  fig.update_layout(title='News Article Word Cloud [Stemmed]', margin = dict(l=0,r=0,t=40,b=0) )
  fig2 = pio.to_html(fig, full_html=False)

  if include == "Yes":
    import world_bank_data as wb
    import wbdata
    def check_wbdb_online():
      try:
        src = wb.get_sources()[['name','lastupdated']].drop(index = '85')
        return 'Online'
      except:
        return 'Offline'
    if check_wbdb_online() == 'Offline':
      return render_template_string(HTML_TEMPLATE5, error = "API ENDPOINT ERROR", textbox="WORLD BANK DATA V2 (TEMPORARILY UNAVAILABLE)")
    src = wb.get_sources()[['name','lastupdated']].drop(index = '85')
    src['amt'] = [194, 1516, 36, 5, 574, 1745, 8450, 115, 1277, 36, 474, 29, 132, 564, 1800, 256, 166, 1, 3313, 3588, 98, 21, 108, 131, 678, 11, 211, 3, 420, 189, 185, 36, 274, 408, 2, 28, 2778, 13, 146, 2, 4, 47, 27, 302, 315, 19, 104, 129, 347, 2, 47, 19, 71, 1, 1, 47, 21, 16, 574, 111, 72, 473, 746, 432, 43, 71, 47, 43, 1577, 43]
    ctry = wbdata.get_countries()######## fix pls
    choice = client.models.generate_content(model="gemini-2.5-flash-lite",contents=f" Data: [{prompt}]. Options: [{src}]. Read but do not print these instructions in output: Read the data and choose the most relevant option from the given options. Print only id number, no chit-chat. Filter out everything that is not a number. DO NOT add in hallucinated noise. Maximum {int(amt)} choices, only choose frequently updated sources that contains less than 170 indicators, very strongly advised to consider sources within this list first(for regularity and time taken): [83,67,3,15,27,54,59,66,67,68,70,75,79]. Leave 4 nextlines after response. DO NOT label using numbers, instead use *")
    choice = choice.text

    try:
      choice = choice.split('\n') #uncleaned
    except:
      pass

    cc = client.models.generate_content(model="gemini-2.5-flash",contents=f" Article: [{prompt}]. Options: [{ctry}]. Read but do not print these instructions in output: Use the article as context and choose the 5 most relevant countries (to the article) from the given options. Print only id code, no chit-chat. Filter out everything that is not a number. DO NOT add in hallucinated noise. Leave 4 nextlines after response. DO NOT label using numbers, instead use *")
    cc = cc.text
    try:
      cc = cc.split('\n') #uncleaned
    except:
      pass

    allind = []
    ac = []

    for sep in choice:
        if sep.strip() != "":
          sep = re.sub(r'\\[a-zA-Z]+|[\${}*#]', '', sep)
          try:
            print('good')
            ind = wb.get_indicators(source=str(sep))
          except:
            print('err')
            ind = wb.get_indicators(source=2)
          ic = client.models.generate_content(model="gemini-2.5-flash-lite",contents=f" Data: [{prompt}]. Options: [{ind}]. Read but do not print these instructions in output: The given data is a news article. The given options are world data indicators. Read the data and choose the most relevant indicators from the given options. Print only id code, no chit-chat. Filter out everything that is not a number. DO NOT add in hallucinated noise. There is no maximum number of choices, but I would prefer if you limit the amount to 5. Leave 4 nextlines after response. DO NOT label using numbers, instead use *")
          ic = ic.text
          ic = ic.split('\n')
          for i in ic:
            if i.strip() != "":
              i = re.sub(r'\\[a-zA-Z]+|[\${}*#]', '', i)
              i = re.sub(' ', '', i)
              allind.append(i)


    for i in cc:
      if i.strip() != "":
        i = re.sub(r'\\[a-zA-Z]+|[\${}*#]', '', i)
        i = re.sub(' ', '', i)
        ac.append(i)

    allind = list(set(allind))
    ac = list(set(ac))

    def check_ind(ind):
      try:
        wbdata.get_dataframe({ind:'Checking An indicator'}, country=['USA', 'AUS'])
        return 'No Err'
      except:
        return 'Err'

    indict = {} #make all indicators list selected (allind) into a dictionary of recorded inds with names
    for i in allind:
      try:

        check = check_ind(i)
        if check == 'No Err':
          print('ind good')
          df_name = wb.get_indicators().loc[i,'name']
          try:
            indict[i] = df_name.iloc[1]
          except:
            indict[i] = df_name
        elif check == 'Err':
          print('ind err')
          del allind[allind.index(i)]
      except:
        print('check error and name err')
        print(i)
        pass

    import plotly.express as px

    wbplots = []
    wbdesc = []
    for i in indict:
      print({i:indict[i]})
      country_codes = [
      "ABW", "AFE", "AFG", "AFR", "AFW", "AGO", "ALB", "AND", "ARB", "ARE", "ARG", "ARM",
      "ASM", "ATG", "AUS", "AUT", "AZE", "BDI", "BEA", "BEC", "BEL", "BEN", "BFA", "BGD",
      "BGR", "BHI", "BHR", "BHS", "BIH", "BLA", "BLR", "BLZ", "BMN", "BMU", "BOL", "BRA",
      "BRB", "BRN", "BSS", "BTN", "BWA", "CAA", "CAF", "CAN", "CEA", "CEB", "CEU", "CHE",
      "CHI", "CHL", "CHN", "CIV", "CLA", "CME", "CMR", "COD", "COG", "COL", "COM", "CPV",
      "CRI", "CSA", "CSS", "CUB", "CUW", "CYM", "CYP", "CZE", "DEA", "DEC", "DEU", "DJI",
      "DLA", "DMA", "DMN", "DNK", "DNS", "DOM", "DSA", "DSF", "DSS", "DZA", "EAP", "EAR",
      "EAS", "ECA", "ECS", "ECU", "EGY", "EMU", "ERI", "ESP", "EST", "ETH", "EUU", "FCS",
      "FIN", "FJI", "FRA", "FRO", "FSM", "FXS", "GAB", "GBR", "GEO", "GHA", "GIB", "GIN",
      "GMB", "GNB", "GNQ", "GRC", "GRD", "GRL", "GTM", "GUM", "GUY", "HIC", "HKG", "HND",
      "HPC", "HRV", "HTI", "HUN", "IBB", "IBD", "IBT", "IDA", "IDB", "IDN", "IDX", "IMN",
      "IND", "INX", "IRL", "IRN", "IRQ", "ISL", "ISR", "ITA", "JAM", "JOR", "JPN", "KAZ",
      "KEN", "KGZ", "KHM", "KIR", "KNA", "KOR", "KWT", "LAC", "LAO", "LBN", "LBR", "LBY",
      "LCA", "LCN", "LDC", "LIC", "LIE", "LKA", "LMC", "LMY", "LSO", "LTE", "LTU", "LUX",
      "LVA", "MAC", "MAF", "MAR", "MCO", "MDA", "MDE", "MDG", "MDV", "MEA", "MEX", "MHL",
      "MIC", "MKD", "MLI", "MLT", "MMR", "MNA", "MNE", "MNG", "MNP", "MOZ", "MRT", "MUS",
      "MWI", "MYS", "NAC", "NAF", "NAM", "NCL", "NER", "NGA", "NIC", "NLD", "NOR", "NPL",
      "NRS", "NRU", "NXS", "NZL", "OED", "OMN", "OSS", "PAK", "PAN", "PER", "PHL", "PLW",
      "PNG", "POL", "PRE", "PRI", "PRK", "PRT", "PRY", "PSE", "PSS", "PST", "PYF", "QAT",
      "ROU", "RRS", "RUS", "RWA", "SAS", "SAU", "SDN", "SEN", "SGP", "SLB", "SLE", "SLV",
      "SMR", "SOM", "SRB", "SSA", "SSD", "SSF", "SST", "STP", "SUR", "SVK", "SVN", "SWE",
      "SWZ", "SXM", "SXZ", "SYC", "SYR", "TCA", "TCD", "TEA", "TEC", "TGO", "THA", "TJK",
      "TKM", "TLA", "TLS", "TMN", "TON", "TSA", "TSS", "TTO", "TUN", "TUR", "TUV", "TZA",
      "UGA", "UKR", "UMC", "URY", "USA", "UZB", "VCT", "VEN", "VGB", "VIR", "VNM", "VUT",
      "WLD", "WSM", "XKX", "XZN", "YEM", "ZAF", "ZMB", "ZWE"] ## all 296 code ids
      try:
        for j in ac:
          try:
            country_codes.index(j)
          except:
            ac.remove(j)
        df = wbdata.get_dataframe({i:indict[i]}, country=ac)
        print('df ok')
        dfu = df.unstack(level=0)
        print('dfu ok')
        print(dfu)
        # Ensure dfu is a DataFrame with a proper index (dates) and columns (countries)
        # px.line can handle this wide format directly by plotting each column as a separate line
        dfu = dfu[indict[i]]
        print(dfu)
        if (dfu.notna().values == True).sum() / ( dfu.shape[1]) >= 2:
          fig = px.line(dfu,x=dfu.index,  y=dfu.columns,title=indict[i])
          first = dfu.loc[dfu.notna().any(axis=1)].index[0]
          last = dfu.loc[dfu.notna().any(axis=1)].index[-1]
          fig.update_layout(xaxis=dict(range=[list(dfu.index).index(first),list(dfu.index).index(last)]))
          plot = fig.to_html(full_html=False, include_plotlyjs='cdn')
          print('plots good')
          wbplots.append((indict[i],plot))
          if include_desc == 'Yes':
            plot_desc = client.models.generate_content(model="gemini-2.5-flash-lite",contents=f"Read this as news article: [{prompt}]. \n\nRead this dataframe which is used for a line chart called {indict[i]}: {dfu} \n\nRead these instructions but do not print them: Print only an interpretation of the line chart in the given context, no chit-chat. Filter out all boilerplate words and noise. DO NOT add in hallucinated noise.")
            plot_desc = re.sub(r'\\[a-zA-Z]+|[\${}*#]', '', plot_desc.text)
            wbdesc.append((indict[i],plot_desc))
          else:
            wbdesc.append((indict[i],'NO DESCRIPTION BY USER'))
          #fig.show()
          #dfu.plot()
          #plt.title(indict[i])
        else:
          print('not enough data err')
      except:
        print('no plots err')
        wbdesc.append(('NO PLOTS NO DESCRIPTION ','NO PLOTS NO DESCRIPTION '))
        wbplots.append(('ERR_NO RELEVANT PLOTS','ERR_NO RELEVANT PLOTS'))
        pass #no wb data, no point in visualising nil
  else:
    wbplots = []
    wbdesc = []
    wbdesc.append(('NO PLOTS NO DESCRIPTION ','NO DESCRIPTION BY USER'))
    wbplots.append(('USER_NO PLOTS','USER_NO PLOTS'))

  end = time.time()
  print(end-start, ' seconds taken') #wc2 used to be fig2. Now the position in webpage is entity frequency bar (ef).
  return render_template_string(HTML_TEMPLATE3, summary = summary, reply=reply, table1 = bdata1, wc1 = fig1, wc2 = ef, reply2 = reply2, table2=bdata2, wbplots = wbplots, desc = wbdesc, show_section=True)

@app.route('/find')
def find():
  return render_template_string(HTML_TEMPLATE4, reply1="", reply2='',reply3='')

@app.route('/search', methods=['POST'])
def search():
  import time
  from google import genai
  from google.genai.types import HttpOptions
  from google.genai import types
  start = time.time()

  topic = request.form["topic"]
  region = request.form["region"]
  num = request.form["num"]
  sample = request.form["sample"]
  amt = request.form["amt"]
  try:
    include_desc = request.form["include_desc"]
  except:
    include_desc = 'No'

  try:
    include = request.form["include"]
  except:
    include = 'No'
  if topic == "":
    return render_template_string(HTML_TEMPLATE5, error = "TEXTBOX ERROR", textbox="TOPIC")
  from ddgs import DDGS
  def news(
    keywords: str,
    region: str = "us-en",
    safesearch: str = "moderate",
    timelimit: str | None = None,
    max_results: int | None = None,
    ) -> list[dict[str, str]]:
    """DuckDuckGo news search. Query params: https://duckduckgo.com/params.

    Args:
        keywords: keywords for query.
        region: us-en, uk-en, ru-ru, etc. Defaults to "us-en".
        safesearch: on, moderate, off. Defaults to "moderate".
        timelimit: d, w, m. Defaults to None.
        max_results: max number of results. If None, returns results only from the first response. Defaults to None.

    Returns:
        List of dictionaries with news search results.
    """
  results = DDGS().news(keywords=topic, region=region, safesearch="off", timelimit="m", max_results=int(sample), query= topic)

  client = genai.Client(http_options=HttpOptions(api_version="v1"),api_key=)

  #tree1
  texts=[]
  feeds=[]
  for i in results:
    texts.append(i['body'])
    feeds.append(i['url'])
  response = client.models.generate_content(model="gemini-2.5-flash-lite",contents=f"Extract 15 important key words from {" ".join(texts)}. You can create new strong term from combining weaker terms. Filter out extremely broad and generic terms. Exclusion list: {topic}. Give response in a list without scores. DO NOT label using numbers, instead use *  .DO NOT use acronyms or initialisms, always specify full phrase")
  response = re.sub(r"[\[\(\{].*?[\]\)\}]", "", response.text)
  sch_key = response.split("\n* ")[1:-2]

  #tree2
  for i in sch_key:
    results = DDGS().news(keywords=i, region=region, safesearch="off", timelimit="m", max_results=int(num), query= i)

    #text2 = []
    for i in results:
      texts.append(i['body'])
      feeds.append(i['url'])

  texts = list(set(texts))
  feeds = list(set(feeds))

  response = client.models.generate_content(model="gemini-2.5-flash-lite",contents=f"Extract 10 important key words from {" ".join(texts)}. You can create new strong term from combining weaker terms. Filter out extremely broad and generic terms. Exclusion list: {topic}. Give response in a list without scores. DO NOT label using numbers, instead use * .DO NOT use multiple ** in a sequence. You can use acronyms or initialisms given that you always specify the abbreviated name")
  response = re.sub(r"[\[\(\{].*?[\]\)\}]", "", response.text)
  sch_key3 = response.split("\n* ")[1:-2]
  prompt = " ".join(texts)
  reply1 = client.models.generate_content(model="gemini-2.5-flash-lite",contents=f"Your Data to read: {" ".join(texts)}. Your Topic to analyse: {topic}.  Read but do not print these instructions in output: Print only an executive report, 1 to 2 paragraphs per section, include numbers if any, no chit-chat. Filter out all boilerplate words and noise. DO NOT add in hallucinated noise. DO NOT add date in title. Leave 4 nextlines after response. ")
  reply1 = response = re.sub(r'\\[a-zA-Z]+|[\${}*#]', "", reply1.text)
  reply2 = client.models.generate_content(model="gemini-2.5-flash-lite",contents=f"Your Data to read: {" ".join(texts)}. Your Topic to analyse: {topic}. Your Sections: {sch_key3}. Read but do not print these instructions in output: Print only an executive report, 1 to 2 paragraphs per section, include numbers if any, no chit-chat. Filter out all boilerplate words and noise. DO NOT add in hallucinated noise. DO NOT add date in title. Leave 4 nextlines after response. ")
  reply2 = response = re.sub(r'\\[a-zA-Z]+|[\${}*#]', "", reply2.text)
  reply3 = client.models.generate_content(model="gemini-2.5-flash-lite",contents=f"Your Data to read: {" ".join(texts)}. Your Topic to analyse: {topic}.  Read but do not print these instructions in output: Print only a report, recommend strategies and analyze, include numbers if any, no chit-chat. Filter out all boilerplate words and noise. DO NOT add in hallucinated noise. DO NOT add date in title. Leave 4 nextlines after response. ")
  reply3 = response = re.sub(r'\\[a-zA-Z]+|[\${}*#]', "", reply3.text)

  #wbplots = [] #this is reply variable used by inside 'if' section,
  if include == "Yes":
    import world_bank_data as wb
    import wbdata
    def check_wbdb_online():
      try:
        src = wb.get_sources()[['name','lastupdated']].drop(index = '85')
        return 'Online'
      except:
        return 'Offline'
    if check_wbdb_online() == 'Offline':
      return render_template_string(HTML_TEMPLATE5, error = "API ENDPOINT ERROR", textbox="WORLD BANK DATA V2 (TEMPORARILY UNAVAILABLE)")

    src = wb.get_sources()[['name','lastupdated']].drop(index = '85')
    src['amt'] = [194, 1516, 36, 5, 574, 1745, 8450, 115, 1277, 36, 474, 29, 132, 564, 1800, 256, 166, 1, 3313, 3588, 98, 21, 108, 131, 678, 11, 211, 3, 420, 189, 185, 36, 274, 408, 2, 28, 2778, 13, 146, 2, 4, 47, 27, 302, 315, 19, 104, 129, 347, 2, 47, 19, 71, 1, 1, 47, 21, 16, 574, 111, 72, 473, 746, 432, 43, 71, 47, 43, 1577, 43]
    src = src.loc[['83','67','3','15','27','54','59','66','67','68','70','75','79']]
    choice = client.models.generate_content(model="gemini-2.5-flash-lite",contents=f" Data: [{prompt}]. Options: [{src}]. Read but do not print these instructions in output: Read the data and choose the most relevant option from the given options. Print only id number, no chit-chat. Filter out everything that is not a number. DO NOT add in hallucinated noise. Maximum {int(amt)} choices, only choose frequently updated sources that contains less than 170 indicators. Leave 4 nextlines after response. DO NOT label using numbers, instead use *")
    choice = choice.text

    try:
      choice = choice.split('\n') #uncleaned
    except:
      pass

    newchoice = []
    for sep in choice:
      sep = re.sub(r'\\[a-zA-Z]+|[\${}*#]', '', sep)
      newchoice.append(sep )

    ctry = wbdata.get_countries()
    cc = client.models.generate_content(model="gemini-2.5-flash",contents=f" Article: [{prompt}]. Options: [{ctry}]. Read but do not print these instructions in output: Use the article as context and choose the 5 most relevant countries (to the article) from the given options. Print only id code, no chit-chat. Filter out everything that is not a number. DO NOT add in hallucinated noise. Leave 4 nextlines after response. DO NOT label using numbers, instead use *")
    cc = cc.text

    try:
      cc = cc.split('\n') #uncleaned
    except:
      pass

    allind = []
    ac = []
    for n in newchoice: #reduce scope of the sources since some sources are actually archived and disconnected, 2 and 3 are most regular.
      ind = wb.get_indicators(source=n)
      ic = client.models.generate_content(model="gemini-2.5-flash-lite",contents=f" Data: [{prompt}]. Options: [{ind}]. Read but do not print these instructions in output: Read the data and choose the most relevant economic indicators (to the article given in data) from the given options. Print only id code, no chit-chat. Filter out everything that is not a number. DO NOT add in hallucinated noise. There is no maximum number of choices, but I would prefer if you limit the amount to 2. Leave 4 nextlines after response. DO NOT label using numbers, instead use *")
      ic = ic.text
      ic = ic.split('\n')
      for i in ic:
        if i.strip() != "":
          i = re.sub(r'\\[a-zA-Z]+|[\${}*#]', '', i)
          i = re.sub(' ', '', i)
          allind.append(i)

    for i in cc: #clean selected countries
      if i.strip() != "":
        i = re.sub(r'\\[a-zA-Z]+|[\${}*#]', '', i)
        i = re.sub(' ', '', i)
        ac.append(i)

    allind = list(set(allind)) #ensure all are unique
    ac = list(set(ac))

    def check_ind(ind):
      try:
        wbdata.get_dataframe({ind:'Checking An indicator'}, country=['USA', 'AUS'])
        return 'No Err'
      except:
        return 'Err'

    indict = {} #make all indicators list selected (allind) into a dictionary of recorded inds with names
    for i in allind:
      try:

        check = check_ind(i)
        if check == 'No Err':
          print('ind good')
          try:
            indict[i] = wb.get_indicators().loc[i,'name'].iloc[1]
          except:
            indict[i] = wb.get_indicators().loc[i,'name']
        elif check == 'Err':
          print('ind err')
          del allind[allind.index(i)]
      except:
        print('check error and name err')
        print(i)
        pass

    import plotly.express as px

    wbplots = []
    wbdesc = []
    for i in indict:
      print({i:indict[i]})
      country_codes = [
      "ABW", "AFE", "AFG", "AFR", "AFW", "AGO", "ALB", "AND", "ARB", "ARE", "ARG", "ARM",
      "ASM", "ATG", "AUS", "AUT", "AZE", "BDI", "BEA", "BEC", "BEL", "BEN", "BFA", "BGD",
      "BGR", "BHI", "BHR", "BHS", "BIH", "BLA", "BLR", "BLZ", "BMN", "BMU", "BOL", "BRA",
      "BRB", "BRN", "BSS", "BTN", "BWA", "CAA", "CAF", "CAN", "CEA", "CEB", "CEU", "CHE",
      "CHI", "CHL", "CHN", "CIV", "CLA", "CME", "CMR", "COD", "COG", "COL", "COM", "CPV",
      "CRI", "CSA", "CSS", "CUB", "CUW", "CYM", "CYP", "CZE", "DEA", "DEC", "DEU", "DJI",
      "DLA", "DMA", "DMN", "DNK", "DNS", "DOM", "DSA", "DSF", "DSS", "DZA", "EAP", "EAR",
      "EAS", "ECA", "ECS", "ECU", "EGY", "EMU", "ERI", "ESP", "EST", "ETH", "EUU", "FCS",
      "FIN", "FJI", "FRA", "FRO", "FSM", "FXS", "GAB", "GBR", "GEO", "GHA", "GIB", "GIN",
      "GMB", "GNB", "GNQ", "GRC", "GRD", "GRL", "GTM", "GUM", "GUY", "HIC", "HKG", "HND",
      "HPC", "HRV", "HTI", "HUN", "IBB", "IBD", "IBT", "IDA", "IDB", "IDN", "IDX", "IMN",
      "IND", "INX", "IRL", "IRN", "IRQ", "ISL", "ISR", "ITA", "JAM", "JOR", "JPN", "KAZ",
      "KEN", "KGZ", "KHM", "KIR", "KNA", "KOR", "KWT", "LAC", "LAO", "LBN", "LBR", "LBY",
      "LCA", "LCN", "LDC", "LIC", "LIE", "LKA", "LMC", "LMY", "LSO", "LTE", "LTU", "LUX",
      "LVA", "MAC", "MAF", "MAR", "MCO", "MDA", "MDE", "MDG", "MDV", "MEA", "MEX", "MHL",
      "MIC", "MKD", "MLI", "MLT", "MMR", "MNA", "MNE", "MNG", "MNP", "MOZ", "MRT", "MUS",
      "MWI", "MYS", "NAC", "NAF", "NAM", "NCL", "NER", "NGA", "NIC", "NLD", "NOR", "NPL",
      "NRS", "NRU", "NXS", "NZL", "OED", "OMN", "OSS", "PAK", "PAN", "PER", "PHL", "PLW",
      "PNG", "POL", "PRE", "PRI", "PRK", "PRT", "PRY", "PSE", "PSS", "PST", "PYF", "QAT",
      "ROU", "RRS", "RUS", "RWA", "SAS", "SAU", "SDN", "SEN", "SGP", "SLB", "SLE", "SLV",
      "SMR", "SOM", "SRB", "SSA", "SSD", "SSF", "SST", "STP", "SUR", "SVK", "SVN", "SWE",
      "SWZ", "SXM", "SXZ", "SYC", "SYR", "TCA", "TCD", "TEA", "TEC", "TGO", "THA", "TJK",
      "TKM", "TLA", "TLS", "TMN", "TON", "TSA", "TSS", "TTO", "TUN", "TUR", "TUV", "TZA",
      "UGA", "UKR", "UMC", "URY", "USA", "UZB", "VCT", "VEN", "VGB", "VIR", "VNM", "VUT",
      "WLD", "WSM", "XKX", "XZN", "YEM", "ZAF", "ZMB", "ZWE"] ## all 296 code ids
      try:
        for j in ac:
          try:
            country_codes.index(j)
          except:
            ac.remove(j)
        try:
          print('df good')
          df = wbdata.get_dataframe({i:indict[i]}, country=ac)
        except:
          df = wbdata.get_dataframe({'SP.POP.TOTL':'Population Total'}, country=ac) #fuck it i give up... llm keeps sometimes returning archived indicators
          pass
        dfu = df.unstack(level=0)
        # Ensure dfu is a DataFrame with a proper index (dates) and columns (countries)
        # px.line can handle this wide format directly by plotting each column as a separate line
        dfu = dfu[indict[i]]
        print('dfu ok')
        if (dfu.notna().values == True).sum() / ( dfu.shape[1]) >= 2:
          fig = px.line(dfu,x=dfu.index,  y=dfu.columns,title=indict[i])
          first = dfu.loc[dfu.notna().any(axis=1)].index[0]
          last = dfu.loc[dfu.notna().any(axis=1)].index[-1]
          fig.update_layout(xaxis=dict(range=[list(dfu.index).index(first),list(dfu.index).index(last)]))
          plot = fig.to_html(full_html=False, include_plotlyjs='cdn')
          print('plots good')
          wbplots.append((indict[i],plot))
          if include_desc == 'Yes':
           plot_desc = client.models.generate_content(model="gemini-2.5-flash-lite",contents=f"Read this as news article: [{prompt}]. \n\nRead this dataframe which is used for a line chart called {indict[i]}: {dfu} \n\nRead these instructions but do not print them: Print only an interpretation of the line chart in the given context, no chit-chat. Filter out all boilerplate words and noise. DO NOT add in hallucinated noise.")
           plot_desc = re.sub(r'\\[a-zA-Z]+|[\${}*#]', '', plot_desc.text)
           wbdesc.append((indict[i],plot_desc))
          else:
            wbdesc.append((indict[i],'NO DESC BY USER'))
          #fig.show()
          #dfu.plot()
          #plt.title(indict[i])
        else:
          print('not enough data err')
          def short_search():
            print('not enough data err, trying replacement')
            try:
              src = wb.get_sources()[['name','lastupdated']].drop(index = '85')
              src['amt'] = [194, 1516, 36, 5, 574, 1745, 8450, 115, 1277, 36, 474, 29, 132, 564, 1800, 256, 166, 1, 3313, 3588, 98, 21, 108, 131, 678, 11, 211, 3, 420, 189, 185, 36, 274, 408, 2, 28, 2778, 13, 146, 2, 4, 47, 27, 302, 315, 19, 104, 129, 347, 2, 47, 19, 71, 1, 1, 47, 21, 16, 574, 111, 72, 473, 746, 432, 43, 71, 47, 43, 1577, 43]
              src = src.loc[['83','67','3','15','27','54','59','66','67','68','70','75','79']]
              src = src.sort_values(by=['lastupdated','amt'],ascending=False)
              src.loc[src['amt'] <= 30].head()['name'].tolist()
              choice = client.models.generate_content(model="gemini-2.5-flash-lite",contents=f" Data: [{prompt}]. Options: [{src}]. Read but do not print these instructions in output: Read the data and choose the most relevant option from the given options. Print only id number, no chit-chat. Filter out everything that is not a number. DO NOT add in hallucinated noise. Maximum {int(amt)} choices, only choose frequently updated sources that contains less than 170 indicators. Leave 4 nextlines after response. DO NOT label using numbers, instead use *")
              choice = choice.text
              try:
                choice = choice.split('\n') #uncleaned
              except:
                pass

              newchoice = []
              for sep in choice:
                sep = re.sub(r'\\[a-zA-Z]+|[\${}*#]', '', sep)
                newchoice.append(sep )
                allind = []
                for n in newchoice: #reduce scope of the sources since some sources are actually archived and disconnected, 2 and 3 are most regular.
                  ind = wb.get_indicators(source=n)
                  ic = client.models.generate_content(model="gemini-2.5-flash-lite",contents=f" Data: [{prompt}]. Options: [{ind}]. Read but do not print these instructions in output: Read the data and choose the most relevant economic indicators (to the article given in data) from the given options. Print only id code, no chit-chat. Filter out everything that is not a number. DO NOT add in hallucinated noise. There is no maximum number of choices, but I would prefer if you limit the amount to 2. Leave 4 nextlines after response. DO NOT label using numbers, instead use *")
                  ic = ic.text
                  print(ic)
                  try:
                    ic = ic.split('\n')
                    for i in ic:
                      if i.strip() != "":
                        i = re.sub(r'\\[a-zA-Z]+|[\${}*#]', '', i)
                        i = re.sub(' ', '', i)
                        allind.append(i)
                  except:
                    if i.strip() != "":
                      i = re.sub(r'\\[a-zA-Z]+|[\${}*#]', '', i)
                      i = re.sub(' ', '', i)
                      allind.append(i)
                    pass
                  allind = list(set(allind)) #ensure all are unique
                  print(allind)
                  indict = {} #make all indicators list selected (allind) into a dictionary of recorded inds with names
                  for i in allind:
                    try:

                      check = check_ind(i)
                      if check == 'No Err':
                        print('ind good')
                        try:
                          indict[i] = wb.get_indicators().loc[i,'name'].iloc[1]
                        except:
                          indict[i] = wb.get_indicators().loc[i,'name']
                      elif check == 'Err':
                        print('ind err')
                        del allind[allind.index(i)]
                    except:
                      print('check error and name err')
                      print(i)
                      pass
                for i in indict:
                  print({i:indict[i]})
                  dfu = wbdata.get_dataframe({i:indict[i]}, country=ac).unstack(level=0)
                  dfu = dfu[indict[i]]
                  if (dfu.notna().values == True).sum() / ( dfu.shape[1]) >= 2:
                    fig = px.line(dfu,x=dfu.index,  y=dfu.columns,title=indict[i])
                    first = dfu.loc[dfu.notna().any(axis=1)].index[0]
                    last = dfu.loc[dfu.notna().any(axis=1)].index[-1]
                    fig.update_layout(xaxis=dict(range=[list(dfu.index).index(first),list(dfu.index).index(last)]))
                    plot = fig.to_html(full_html=False, include_plotlyjs='cdn')
                    print('plots good')
                    wbplots.append((indict[i],plot))
                    if include_desc == 'Yes':
                      plot_desc = client.models.generate_content(model="gemini-2.5-flash-lite",contents=f"Read this as news article: [{prompt}]. \n\nRead this dataframe which is used for a line chart called {indict[i]}: {dfu} \n\nRead these instructions but do not print them: Print only an interpretation of the line chart in the given context, no chit-chat. Filter out all boilerplate words and noise. DO NOT add in hallucinated noise.")
                      plot_desc = re.sub(r'\\[a-zA-Z]+|[\${}*#]', '', plot_desc.text)
                      wbdesc.append((indict[i],plot_desc))
                    else:
                      wbdesc.append((indict[i],'NO DESCRIPTION BY USER'))
            except:
              print('remedy failed, I give up')
              wbplots = []
              wbdesc = []
              wbdesc.append(('NO PLOTS NO DESCRIPTION ','NO PLOTS NO DESCRIPTION'))
              wbplots.append(('USER_NO PLOTS FOUND','USER_NO PLOTS FOUND'))

          short_search()
      except:
        print('too little data err')
        wbdesc.append(('NO PLOTS NO DESCRIPTION ','NO PLOTS NO DESCRIPTION'))
        wbplots.append(('ERR_TOO LITTLE DATA FOR PLOTS OR NO DATA','ERR_TOO LITTLE DATA FOR PLOTS OR NO DATA'))
        pass #no wb data, no point in visualising nil
  else:
    wbplots = []
    wbdesc = []
    wbdesc.append(('NO DESCRIPTION BY USER','NO DESCRIPTION BY USER'))
    wbplots.append(('USER_NO PLOTS','USER_NO PLOTS'))

  end = time.time()
  print(end-start, ' seconds taken')
  return render_template_string(HTML_TEMPLATE4, reply1=reply1, reply2=reply2, reply3=reply3, feeds = feeds, wbplots = wbplots, desc = wbdesc, show_section=True)

from pyngrok import ngrok

# Authenticate ngrok (you might need to get an auth token from ngrok.com)
ngrok.set_auth_token()

# Start ngrok tunnel on the port your Flask app will run on (e.g., 5000)
public_url = ngrok.connect(addr=5000,domain=).public_url
print(f"Flask app exposed at: {public_url}")

# Run your Flask application
app.run(port=5000)
